apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::376644760842:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QNYQ3O7H1K84
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::376644760842:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-21T20:32:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1978"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ea840bd8-264c-4f22-9d0c-d6346c84292b
